### PR TITLE
Add grpc-gateway-ts support

### PR DESCRIPTION
**Pull request by heartless-clown**
Added support for protoc-gen-grpc-gateway-ts plugin.
Added resolve directive to proto_ts_library rule.
Added macro to generate well-know-types targets for typescript.
Updated ts-proto version to 1.115.4.
Updated examples and README.

### CODE REVIEW

**Comment by pcj** [comment]
Can you change the target branch to `heartless-clown:grpc-gateway`. Will be easier to review and branch will be automatically updated if that one is merged.

**Comment by heartless-clown** [comment]
I don't believe this is possible, or I don't know how.
image

**Comment by pcj** [comment]
Ah OK, you are right.  You'd have to push the branch directly to this repo, but that a different auth profile.

**Comment by pcj** [comment]
CI: https://buildkite.com/bazel/stackb-rules-proto/builds?branch=heartless-clown%3Agrpc-gateway

**Comment by pcj** [comment]
Closing due to age, but let's re-open if still actively used.

**Pull request closed without merging**
