### PR TITLE
issue 48 upgrade the declaration of the nuget packages

### PR DESCRIPTION
**Pull request by nmalsang**
update the declaration of the nuget packages to be consistent with the dotnet_rules this means replace some lists by maps

I add unit tests for .net core.

### CODE REVIEW

**Comment by pcj** [comment]
@nmalsang This looks great, really appreciate having some `C#` interest/expertise here.  

In this PR you have a new directory `core_example/`.  Is there a reason not to make this the main `example/`?

**Comment by nmalsang** [comment]
@pcj Well I can merge it under example. I add the core_example folder because as there are WORKSPACE file under the example folder, I need to register correctly .Net Core with the following lines:
 framework = "v2.1.503"
dotnet_register_toolchains(core_version=framework)
core_register_sdk(core_version="{}".format(framework), name = "core_sdk")
And because I do not have .Net Framework on my machine, so it was easier for me. 
But just let me know if you want me to remove core_example and set correctly the WORKSPACE files under the "example" folder.

**Comment by nmalsang** [comment]
@pcj  I merged core_example with example.  I let you review it. Thanks

**Comment by pcj** [comment]
I think it looks good, let's merge it.  Thanks!

**Pull request merged**
