### PR TITLE
python: Provide python rules via CrossResolve.

### PR DESCRIPTION
**Pull request by DolceTriade**
This allows rules_python's gazelle plugin to find python rules generated by rules_proto allowing for a fully gazelle'ified experience working with protos with Python.

### CODE REVIEW

**Review by ankit-gautam23 — APPROVED** [review]
LGTM

**Comment by DolceTriade** [comment]
@pcj Is this something that is desirable upstream?

**Comment by pcj** [comment]
Apologies for the long delay, yes this is desireable.  Let's look to get it rebased.

**Comment by DolceTriade** [comment]
Rebased. Also ran gazelle.

**Comment by DolceTriade** [comment]
Should I undo the irrelevant gazelle changes?

**Comment by pcj** [comment]
No it’s fine, just not something you should have to think about.

---
Paul Cody Johnston
Principal - Stack.Build

**Comment by pcj** [comment]
CI is failing, but it's not due to this PR.  I'm going to merge this and disable that test.

**Pull request merged**
