### PR TITLE
feat: add linter script that purifies text files

### PR DESCRIPTION
**Pull request by qzmfranklin**
Text files with trailing white spaces (one of \t \v \n \r and space)
lead to unnecessary diffs and make merging more difficult.  We should
remove them.

However, developers should NOT be drained on such repetitive tasks as
'removing trailing white spaces'.  Indeed, code reviews should focus on
'what was said' rather how 'how it was said'.

This comit enables the following workflow:

  - After a fresh clone of this repository, the developer runs the
    following commands to perform a one-time setup of the pre-commit
    hooks for this clone of the repository:

        # https://pre-commit.com/
        sudo pip3 install pre-commit
        pre-commit install

    These commands will install a .git/pre-commit script that searches
    for file .pre-commit-config.yaml in the root directory of this
    repository.

  - Every `git commit` afterwards will trigger the hooks configured in
    the .pre-commit-config.yaml file.  In this case, the python script
    ./tools/lint/purify_text.py will be called to process each staged
    file to strip trailing whitespaces.

  - In the future, if this repository needs more linters and formatters,
    just configure the .pre-commit-config.yaml file to add more or
    modify existing ones.

### CODE REVIEW

**Comment by qzmfranklin** [comment]
Fixes https://github.com/stackb/rules_proto/issues/11

**Comment by pcj** [comment]
Hi @qzmfranklin overall looks good and appreciate your time.  I'm reserving the right to remove the pre-commit hook if it ends up negatively interacting with other tools (buildifier mainly) :).  Note that all the `README.md` files, `{lang}_proto_library.bzl` are generated by the tool `exgen`.  Please run `bazel build //tools/exgen && ./bazel-bin/tools/exgen/linux_amd64_stripped/exgen` (or equivalent mac binary location on your machine) to see that.  A number of the trailing whitespace characters are probably coming from newlines in those go templates that can be fixed up as well.

I'm currently migrating away from travis to a custom bazel ci solution so you can ignore those travis checks for now.

**Comment by pcj** [comment]
Merged #13 if you want to rebase on that.

**Comment by qzmfranklin** [comment]
Hi @pcj 


Appreciate your fast feedback and help!

Per 'reserving the right to remove ...':
Thanks for being open~ For your information, my team have been using buildifier, tslint, clang-format, eslint, yapf, checkstyle, yamllint (~20 hooks) etc. as precomit hooks together with the purify-text one. They coexisted well for the past few months. We have not had an incidence of bad interactions *yet* (they may happen in the future). Let's keep each other notified on this, shall we? I'd like to contribute more of our pre-commit hook configs to this repo.

Per '... are generated by the tool exgen ...':
Thanks for letting me know. I was not aware of that. I am currently thinking that it should be good to trim trailing whitespaces for two reasons: a) trimming does not increase developers' workload because it is automated by the pre-commit hook, and b) trimming would ultimately help reduce unnecessary diffs (longer explanations and examples available at request). But I don't think I am all around on this and would be happy to hear reasons arguing the other way.

**Comment by qzmfranklin** [comment]
Just rebased to the latest `master`.  Please let me know.

**Comment by qzmfranklin** [comment]
ping :D

**Comment by pcj** [comment]
Had wanted to get this through the new CI but that's dragging out, so going ahead and merging this.

**Pull request merged**
