### PR TITLE
Aspects refactoring

### PR DESCRIPTION
**Pull request by aaliddell**
Following on from #83, these are the changes I mentioned.

Main changes:
- ~~Ruby and Python revert to using standard compilation by default. Aspect based compilation rules have been copied to `_aspect` suffix but remain problematic; the issue of duplicate files from #83 persists in the aspect based rules, but is resolved when using the default rules.~~
- Common functions between aspect.bzl and compile.bzl have been extracted to common.bzl
- Python package dependencies have been updated
- Some fixing of newline errors etc, using your linter in /tools as a check
- Updates to rulegen to produce the above changes
- Correct forwarding of args to underlying rules such that behavior now matches the documented args
- Add makefile for building all examples (warning, slow)
- Merged and simplified templates for various languages
- Remove imcompatible flags (see bazelbuild/continuous-integration#726)
- Add test workspaces based on known issues
- Resolve protoc via a toolchain
- Restructured the aspect based compilation to use the proto descriptors
- Updated plugin definitions
- Moved all languages to aspect compilation and removed old transitive compilation
- Python protobuf is pulled directly from com_google_protobuf, negating the need for going to pip
- Go rules importmap is not supported
- Support protoc plugins that produce non-predictable outputs using `ctx.actions.declare_directory`
- Removed compile.bzl based compilation
- Moved to standard bazel_build_rules_nodejs and renamed node to nodejs
- Rust raze deps are now internally managed due to being out-of-date upstream

As a result, these changes will likely close the following issues: #63 #83 #56 #105 #106

Presently I have opened this as a draft PR to see how CI performs and to have the opportunity to discuss what is/isn't useful.

### CODE REVIEW

**Comment by pcj** [comment]
@aaliddell Thanks for all your work on this, really appreciate it.  I won't have time to dig into this for the next few days, but very much interested in the work you are doing.

**Comment by aaliddell** [comment]
No problem, I'm still tweaking things anyway. As far as I can see, the CI failures we're getting are not yet related to the changes, as it's not starting correctly.

**Comment by aaliddell** [comment]
As a bit of an update: aspect based compilation should be feasible (and required to fix some of the open issues on this repo) but requires some changes to the end-user usage of the rules and a fair amount of refactoring of rulegen. So far the changes have maintained the present usage, so this would be a step further.

**Comment by pcj** [comment]
Clearly I'm not totally understanding the weaknesses of the current aspect implementation, what are shortcomings as you see it?

**Comment by aaliddell** [comment]
Actually not that much needs changing with the aspect implementation itself, besides the issue with target directories that I started all this for (#83) and I haven't actually addressed in the aspect implementation yet :roll_eyes: . The changes come in the removal of some of the attrs on the user-facing rules that we cannot propagate to the aspect implementation (e.g. plugin options) and should come in via the plugins instead.

**Comment by manazhao** [comment]
@aaliddell Thanks for your work on fixing the issues. When will your fixes be merged into the master branch? I'm very looking forward to seeing issue #106 to be fixed and I can continue to work on my project. Please let me know how I can help on this. Thank you very much!

**Comment by aaliddell** [comment]
At this point this has become rather a major rewrite of most of rules_proto to adopt aspect compilation across the board and update dependencies, which unfortunately includes some breaking changes to existing users (documented above, mostly changes to workspace). Therefore, I don't know if this work will be merged to master as a 'version 2.0' or exist as its own fork; that'll be a discussion here once I remove the 'draft' status of this PR but can begin whenever there's interest.

As for timing: most of the hard work has been done in the 193 (oh god) commits so far, just the remaining 10% is taking an unreasonable amount of time due to upstream deps and Bazel weirdness etc (looking at you rust and nodejs :unamused:)

**Comment by manazhao** [comment]
@aaliddell Thanks for the explanation! As for issues like #106, which of your commits are the fix? I'm wondering whether it's possible to merge those commits to the master branch. I feel these fixes are already very useful for the users. @pcj , what do you think?

**Comment by aaliddell** [comment]
Effectively read to unmark as draft, as most work is done now. I have updated the original PR comment with the change summary. The remaining CI failures appear to be Windows and Mac compile/link errors, but I'll continue to have a look if there's something obvious to fix. Since BuildKite seems to have stopped sending statuses, the latest build is here: https://buildkite.com/bazel/rules-proto/builds/227#42f08e66-23a0-4945-8053-e3dac260e349

Since this has become quite a mammoth change, it is perhaps worth looking at the final repo status rather than trying to examine diffs: https://github.com/aaliddell/rules_proto/tree/aspects-dev

@pcj: what are your thoughts?

**Comment by aaliddell** [comment]
I've forked off these changes into https://github.com/rules-proto-grpc/rules_proto_grpc

**Comment by dave-xnor** [comment]
Are you intending to move all protobuf/grpc stuff _out of_ this repo into this other repo permanently?

**Comment by aaliddell** [comment]
At this point it looks like these changes will continue to remain forked in the other repo

**Comment by dave-xnor** [comment]
> At this point it looks like these changes will continue to remain forked in the other repo

Then what is the strategy for users?  Continue to use rules_proto alone, use both together (with the protobuf/grpc rules maybe eventually being removed from here)? Or? 

Reason I'm asking: 
- Currently the situation w.r.t. these rules, the earlier rules_protobuf, rules embedded in the protobuf and grpc repos, and bazel itself is confused and fluid (due to rapid development of bazel).  
- There's documentation pointing all three places, blog posts pointing to all three places, and search results give you all three places.  
- There are "examples" out there of various ages - depending on which example you find you'll find different ways of doing things - yet because of ongoing bazel development none of them actually really work.  
- The different repos (and here I'm speaking of this repo vs rules_protobuf) trail bazel development - in fact you can't use these repos with the latest bazel.  
- You can't even easily say "I'll do things the way grpc does it" hoping to get a repo that builds against grpc because their build system is far too complicated to just pull a few features out of.  (E.g., when setting up a WORKSPACE.)

(At least that's what I've found. I myself am a newcomer to the Bazel community and once you get past the initial tutorials on how to use grpc with one request message and one response message for a single RPC method, all in a single proto file, the learning curve becomes extremely steep.)

A _roadmap_ would be very helpful, especially a roadmap from some authoritative voice w.r.t. the Bazel community. (Perhaps this comment should instead be an issue, but then, an issue where?  Here or over at the bazel repo?)

**Comment by aaliddell** [comment]
I'll preface this by saying I can't give the roadmap of *this* repo, as I am just a contributor. However, I can comment on the present state of the various projects and why this has come about.

Starting with `rules_protobuf`: this was the original project that was superseded by this repo and is now effectively end-of-life. As such, `rules_protobuf` has forwarded users to this repo from the top of its README for a while now. Regrettably it still holds No1 spot in search results, at least for me.

Moving to this repo: it presently has issues with the Python rules (which you have since discovered, originally in #83) and using arguments to `proto_library`, for which this PR initially started. However, as you can see, this diff became a *bit* more substantial since then, as resolving these issues exposed other issues, such as the dependence on `incompatible` flags etc.

At this point, the diff has become substantial enough that the trees have diverged significantly, although the end-user rule 'API' has effectively remained the same unless you're defining your own plugins etc. Presently, the fork is mostly a 'drop-in' replacement to your WORKSPACE, with some renaming of `load` statements in BUILD files also. Regrettably there are some breaking changes due to the move to aspect based compilation, which are documented at https://github.com/rules-proto-grpc/rules_proto_grpc/blob/master/docs/MIGRATION.md. 

In terms of what happens next, this repo continues to exist and doesn't 'lose' the rules. The fork is just an alternative implementation that contains fixes for a number of issues. To confuse things further, there is a similarly named `rules_proto` repo under the bazelbuild org now, but that project only aims to provide implementation of the - presently native - `proto_library` rule and associated functionality, which is why I added the `_grpc` suffix to the fork name.

With regard to merging back to here: whichever way we do it (merge vs fork), these changes have backwards compatible breakages due to moving to aspect compilation, so it's going to require some user changes to adopt (see migration doc above). Therefore, having a clear distinction of two repos that require conscious migration by users might be the least worst solution :unamused: 

-----

To address some other points:

> Currently the situation w.r.t. these rules, the earlier rules_protobuf, rules embedded in the protobuf and grpc repos, and bazel itself is confused and fluid (due to rapid development of bazel).

Bazel itself should hit 1.0 in the next couple of months, which should hopefully bring some relief from the breaking changes and allow the ecosystem to settle a little bit.

> The different repos (and here I'm speaking of this repo vs rules_protobuf) trail bazel development - in fact you can't use these repos with the latest bazel.

Indeed, that was part of what I was trying to solve in this PR; the fork works on latest Bazel at time of comment. As mentioned above `rules_protobuf` is effectively EoL.

> A roadmap would be very helpful, especially a roadmap from some authoritative voice w.r.t. the Bazel community. (Perhaps this comment should instead be an issue, but then, an issue where? Here or over at the bazel repo?)

Unfortunately none of us represent an 'authoritative' voice, we're just volunteering to fill a proto/gRPC shaped hole in the Bazel ecosystem. However the best place to ask may be the mailing list.

**Comment by pcj** [comment]
Hi all, apologies for radio silence here, I was on vacation for 2 weeks and unfortunately injured during a fall and in the hospital for about a week, still on the mend.  I'll still need more time processing this but appreciate all efforts and interest.

**Comment by qzmfranklin** [comment]
Adding a test point here: Internally in our team, I have successfully replaced this repo with [this fork](https://github.com/rules-proto-grpc/rules_proto_grpc).

**Pull request closed without merging**
