### PR TITLE
Fix runfiles error with python_binary plugin tool

### PR DESCRIPTION
**Pull request by Reflexe**
That was caused from the way we resolved runfiles (get_plugin_runfiles), sometimes it wasn't working.

### CODE REVIEW

**Comment by pcj** [comment]
What was the error you were observing that motivated you to write this PR?  I like the changes mostly but the ability to inspect the sandbox before and after has saved me considerable time, not terribly excited about giving that up.

**Comment by Reflexe** [comment]
> What was the error you were observing that motivated you to write this PR? I like the changes mostly but the ability to inspect the sandbox before and after has saved me considerable time, not terribly excited about giving that up.

Shouldn't be a problem to restore this functionality with a protoc wrapper. I'll update this PR. 

The error was an exceptions thrown by bazel's python `py_binary` setup script (script that runs `py_binary`):
```
AssertionError: Cannot find .runfiles directory for X
```

That was caused because of a missing input directory, I tired to fix it by changing `get_plugin_runfiles` but I could not get it to work, so I've decided to write a bigger solution.

**Comment by Reflexe** [comment]
Update: PR updated with a debugging wrapper that should behave just like the previous `ctx.actions.run_shell` solution.

**Comment by pcj** [comment]
Thanks!  Of note I won't have bandwidth to review this for a couple days.

**Comment by Monnoroch** [comment]
Thanks, this PR fixed my RBE issues with a custom plugin! Would love to see it merged upstream.

**Comment by silvergasp** [comment]
Any update on this? I'm not entirely sure why the CI build is failing on github PR. Following the 'Details' link and they all seem to have built.

**Comment by pcj** [comment]
Closing stale PRs and issue, please reopen new one if desired.

**Pull request closed without merging**
