### PR TITLE
build: integrate with bazel 0.22

### PR DESCRIPTION
**Pull request by qzmfranklin**
Bazel 0.22 introduced a major change to the native `proto_library` rule:

    The legacy providers such as `proto` and `direct_sources` are
    re-grouped into the `ProtoInfo` provider.

It necessitates changes such as the following:

    .direct_sources     =>      [ProtoInfo].direct_sources
    .proto              =>      [ProtoInfo].proto

fixes https://github.com/stackb/rules_proto/issues/45

### CODE REVIEW

**Comment by pcj** [comment]
Can the switch from `dep.proto` to `dep[ProtoInfo]` be put behind a version check?  I'd like to support < 0.22 as well.

**Comment by qzmfranklin** [comment]
I have seen such version check in bazel before.
Will work on it in the next few days, assuming it is not urgent for others.

**Comment by gil-cukierman** [comment]
Hello, has there been any progress on the bazel 0.22 compatibility issues? I'm definitely interested in seeing this change land!

**Comment by qzmfranklin** [comment]
@gil-cukierman 

Thanks for the attention and feedback!

If you really need the bazel 0.22 compatibility today, one way to go for now is to checkout the branch used in this PR (if that works for you at all).

If you can wait, here is a little update:

@pcj : 

Disclaimer: This is by no means a fully fledged proposal. Instead, I am just listing what I have found so far and putting up some of my thoughts. So, take it with a grain of salt.

I am considering whether or not we SHOULD support legacy versions of bazel as of this PR. While I am upgrading various components in my project to using bazel 0.22, I found quite a few of them dropped support for older versions of bazel. A notable example is Google's angular (as of [this commit](https://github.com/angular/angular/commit/e4f67dfe660978687f3c925fe6b686f5d533ecb1)).

Another source of information is [bazel's backward compatibility policy](https://docs.bazel.build/versions/master/backward-compatibility.html).  Pasting its summary here for ease of reference:
```text
Every breaking change is guarded with an --incompatible_* flag.
Newly introduced incompatible flags default to off.
For every --incompatible_* flag we have a GitHub issue that explains the change in behavior and provides a migration recipe.
The migration window is at least one release long and is set by the author of the incompatible change.
We announce what set of flags we indend to flip with the next release one release in advance.
APIs and behavior guarded by an --experimental_* flag can change at any time.
Users should never run their production builds with --experimental_* or --incompatible_* flags.
```

However, not all bazel-managed projects are following this paradigm (notably angular). This de facto inhomogeneity makes it difficult for projects with wide third party dependencies to upgrade either bazel or many of its bazel-managed dependencies. More details and reasoning available upon request.

Last but probably not least, I'd like to ask the question: who are the real targeted users of this project?
My current take on it is that people with deep bazel knowledge are probably the most likely users until the bazel ecosystem stabilizes a bit more (maybe when it reaches 1.0?). Those guys are usually on the more aggressive side of things, just like bazel itself. But my view on this is limited, willing to listen different opinions.

**Comment by pcj** [comment]
Superceded by recent changes.

**Pull request closed without merging**
